project:
  type: website
  output-dir: docs

website:
  title: "MICOlab-USF"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: People

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

