project:
  type: website
  output-dir: docs

website:
  title: "MICOlab-USF"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: People
      - href: Manual.qmd
        text: Lab Manual
  page-navigation: true
  
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

