---
title: "Publications"
---

**Submitted**

- Ruggles Howe, L., D'Amore, L., Lopez, C., Shankar, S., **Mars Brisbin, M.** (2025) B-vitamin requirements and phycosphere interactions for the HAB-forming dinoflagellate, *Pyrodinium bahamense* var. *bahamense*. *bioRxiv*. [link](https://www.biorxiv.org/content/10.64898/2025.12.19.695638v2).

- Krinos, A.I., **Mars Brisbin, M.**, Costa, A., Shapiro, A.K., Follows, M.J., Freilich, M., Alexander, H. (2026) Nutrient response strategies drive coastal range shifts of phytoplankton taxa. *bioRxiv*. [link](https://www.biorxiv.org/content/10.64898/2026.01.13.699386v1).

**2025**

- Fussy, Z., Lampe, R., Arrigo, K., Barry, K., **Mars Brisbin, M.**, … Allen, A.E. (2025) Genome-resolved biogeography of Phaeocystales, cosmopolitan bloom-forming algae. *Nature Communications*. [link](https://www.nature.com/articles/s41467-025-63565-1).

-   Kell, R.M., Subhas, A.V., Schanke, N.L., Lees, L.E., Chmiel, R.J., Rao, D., **Mars Brisbin, M.**, Moran, D.M., McIlvin, M.R. Bolinesi, F., Mangoni, O., Casotti, R., Balestra, C., Horner, T.J., Dunbar, R.B., Allen, A.E., DiTullio, G.R., Saito, M.A. (2025) Zinc stimulation of phytoplankton in a low-carbon-dioxide, coastal Antarctic environment: evidence for the Zn hypothesis. *Biogeosciences*. [link](https://bg.copernicus.org/articles/22/5877/2025/).

- **Mars Brisbin, M.**, Acord, M., Davitt, R., Bent, S., Van Mooy, B.A.S., Flaum, E., Norlin, A., Turner, J., Krinos, A., Alexander, H., Saito, M. (2025) Exploring the Phaeosphere: Characterizing the microbiomes of Phaeocystis antarctica colonies from the coastal Southern Ocean and laboratory culture. *Journal of Phycology*. [link](https://onlinelibrary.wiley.com/doi/full/10.1111/jpy.70051). [**Full-text PDF available.**](https://drive.google.com/file/d/1aNpsTGO1u-y2bglaNi5LTHRQ7JA3eeKk/view?usp=sharing) 

- **Mars Brisbin, M.**, McIlvin, M., Wilburn, D., Saunders, J., Cohen, N., Bhatia, M., Kujawinski, E., Searle, B., Saito, M. (2025) Validation and Community Sharing of Ocean Spectral Libraries Generated by Machine Learning for Data Independent Acquisition Ocean Metaproteomic Analyses. *Proteomics*. [link](https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/full/10.1002/pmic.13971). [**Full-text PDF available.**](https://drive.google.com/file/d/1JZ0f-kkXtRru-4x6VLerBDxb65lI1Di2/view?usp=sharing)

**2024**

-   Krinos, A. I., **Mars Brisbin, M.**, Hu, S. K., Cohen, N. R., Rynearson, T. A., Follows, M.J., Schulz, F., Alexander, H. (2024) Missing microbial eukaryotes and misleading meta-omic conclusions. *Nature Communications*. [link](https://doi.org/10.1038/s41467-024-52212-w).

- Saito, M. A., Saunders, J., McIlvin, M., Bertrand, E., Breier, J., **Mars Brisbin, M.**, Colston, S., Compton, J. R., Griffin, T., Hervey, J., Hettich, R., Jagtap, P., Janech, M., Johnson, R., Keil, R., Kleikamp, H., Leary, D., McCain, S., Moore, E., Mehta, S., Moran, D., Neibauer, J., Neely, B., Jakuba, M., Johnson, J., Duffy, M., Herndl, G., Giannone, R., Mueller, R., Nunn, B., Pabst, M., Peters, S., Rajczewski, A., Rowland, E., Searle, B., Van Den Bossche, T., Vora, G. J., Waldbauer, J., Zheng, H., Zhao, Z. (2024) Results from a Multi-Laboratory Ocean Metaproteomic Intercomparison: Effects of LC-MS Acquisition and Data Analysis Procedures. *Biogeosciences*. [link](https://doi.org/10.5194/bg-21-4889-2024) .

-   **Mars Brisbin, M.**, Dudley, K. L., Yonashiro, Y., Mitarai, S., Ares, A. (2024) Urbanization of a subtropical island (Okinawa, Japan) alters physicochemical characteristics and disrupts microbial community dynamics in nearshore ecosystems. *Estuaries & Coasts*. [link](https://link.springer.com/article/10.1007/s12237-024-01366-3).

-   Rao, D., Fussy, Z., **Mars Brisbin, M.**, McIlvin, M. R., Moran, D. M., Allen, A. E., Follows, M. J., Saito, M. A. (2024) Flexible B~12~ ecophysiology of *Phaeocystis antarctica* due to a fusion B~12~-independent methionine synthase with widespread homologues. *PNAS*. [link](https://doi.org/10.1073/pnas.2204075121).

**2023**

-   **Mars Brisbin, M.**, Schofield, A., McIlvin, M. R., Krinos, A. I., Alexander, H., Saito, M. (2023) Vitamin B~12~ conveys a protective advantage to phycosphere-associated bacteria at high temperatures. *ISME Communications*. [link](https://doi.org/10.1038/s43705-023-00298-6).

**2022**

-   **M. Mars Brisbin**, S. Mitarai, M.A. Saito, H. Alexander. (2022) Microbiomes of bloom-forming *Phaeocystis* algae are stable and consistently recruited, with both symbiotic and opportunistic modes. *The ISME Journal* [link](https://www.nature.com/articles/s41396-022-01263-2).

-   L.R. Aoki, **M. Mars Brisbin**, A.G. Hounshell, D.W. Kincaid, E.I. Larson, B.J. Sansom, A.J. Shogren, R.S. Smith, J. Sullivan-Stack. (2022) Preparing aquatic research for an extreme future: Call for improved definitions and responsive, multidisciplinary approaches. *BioScience*. [link](https://academic.oup.com/bioscience/article/72/6/508/6573842).

**2021**

-   C. Uwizeye\*, **M. Mars Brisbin**\*, B. Gallet, F. Chevalier, C. LeKieffre, N. L. Schieber, D. Falconet, D. Wangpraseurt, L. Schertel, H. Stryhanyuk, N. Musat, S. Mitarai, Y. Schwab, G. FInazzi, J. Decelle. (2021)Cytoklepty in the plankton: a host strategy to optimize the bioenergetic machinery of endosymbiotic algae. *PNAS*. [link](https://www.pnas.org/doi/full/10.1073/pnas.2025252118). \* Equal contributions (co-first authors)

**2020**

-   A. Ares\*, **M. Mars Brisbin**\*, K.N. Sato, J.P. Martín, Y. Iinuma, S. Mitarai. (2020) Extreme storms cause rapid but short‐lived shifts in nearshore subtropical bacterial communities. *Environmental Microbiology*. [link](https://ami-journals.onlinelibrary.wiley.com/doi/abs/10.1111/1462-2920.15178). \* Equal contributions (co-first authors)

-   **M. Mars Brisbin**, A.E. Conover, S. Mitarai. (2020) Influence of regional oceanography and hydrothermal activity on protis diversity and community structure in the Okinawa Trough. *Microbial Ecology*. [link](https://link.springer.com/article/10.1007/s00248-020-01583-w).

-   **M. Mars Brisbin**, O.D. Brunner, M.M. Grossmann, S. Mitarai. (2020) Paired high‐throughput, in situ imaging and high‐throughput sequencing illuminate acantharian abundance and vertical distribution. *Limnology and Oceanography*. [link](https://aslopubs.onlinelibrary.wiley.com/doi/full/10.1002/lno.11567).

-   J. Arora, **M. Mars Brisbin**, A.S. Mikheyev. (2020) Effects of microbial evolution dominate those of experimental host-mediated indirect selection. *PeerJ*. [link](https://peerj.com/articles/9350/).

-   D.W. Kincaid, W.S. Beck, J.E. Brandt, **M. Mars Brisbin**, K.J. Farrell, K.L. Hondula, E.I. Larson, A.J. Shogren. (2020) Wikipedia can help resolve information inequality in the aquatic sciences. *Limnology and Oceanography Letters*. [link](https://aslopubs.onlinelibrary.wiley.com/doi/pdf/10.1002/lol2.10168).

**2019**

-   **M. Mars Brisbin**, S. Mitarai. (2019) Differential Gene Expression Supports a Resource‐Intensive, Defensive Role for Colony Production in the Bloom‐Forming Haptophyte, *Phaeocystis globosa*. *Journal of Eukaryotic Microbiology*. [link](https://onlinelibrary.wiley.com/doi/full/10.1111/jeu.12727).

**2018**

-   **M. Mars Brisbin**, L.Y. Mesrop, M.M. Grossmann, S. Mitarai. (2018) Intra-host symbiont diversity and extended symbiont maintenance in photosymbiotic Acantharea (clade F). *Frontiers in Microbiology*. [link](https://www.frontiersin.org/articles/10.3389/fmicb.2018.01998/full).

**2015**

-   **M. Mars Brisbin**, A.E. McElroy, E.P. Espinosa, B. Allam. (2015) Antimicrobial activity in the cuticle of the American lobster, *Homarus americanus*. *Fish & Shellfish Immunology*. [link](https://www.sciencedirect.com/science/article/abs/pii/S1050464815001084).
